### ISSUE TITLE
Crash after repeatedly leaving and restarting.

### ISSUE THREAD

**Issue by kearneyk-up** [kamala21/Kamala21#22]
If I repeatedly start and leave a game, the app crashes after the third "start"

Steps to reproduce:
1. Launch the app
2. Press "Play single player"
3. Press "start game"
4. Select "Leave game" from the menu at the upper right
5. Repeat steps 2-4 until the app crashes. In my testing, this happens the third time "start game" is pressed.

**Comment by kearneyk-up** [comment]
Here is the exception stack trace from logcat:
`01-01 05:08:46.712 4338-4338/com.example.pele_.kamala21 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.pele_.kamala21, PID: 4338
    java.lang.OutOfMemoryError: Failed to allocate a 11675148 byte allocation with 7080480 free bytes and 6MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1155)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:720)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
        at android.content.res.Resources.getDrawable(Resources.java:771)
        at android.content.Context.getDrawable(Context.java:525)
        at android.widget.ImageView.resolveUri(ImageView.java:864)
        at android.widget.ImageView.setImageResource(ImageView.java:448)
        at com.example.pele_.kamala21.spgsActivity.updateCards(spgsActivity.java:520)
        at com.example.pele_.kamala21.spgsActivity.updateScreen(spgsActivity.java:807)
        at com.example.pele_.kamala21.spgsActivity.onDataChange(spgsActivity.java:227)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@16.0.4:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@16.0.4:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@16.0.4:55)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`

**Comment by kamala21** [comment]
Fixed: Uses System.exit(0) instead of finish(); to completely deallocate all memory after leaving activities that use a lot of memory.
